apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-affinity-4
spec:
  replicas: 10
  selector:
    matchLabels:
      app: node-affinity-4
  template:
    metadata:
      labels:
        app: node-affinity-4
    spec:
      containers:
        - name: www-server
          image: hwchiu/netutils
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: kind.zone
                    operator: In
                    values:
                      - zone1
            - weight: 4
              preference:
                matchExpressions:
                  - key: kind.zone
                    operator: In
                    values:
                      - zone2
