apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-affinity-3
spec:
  replicas: 10
  selector:
    matchLabels:
      app: node-affinity-3
  template:
    metadata:
      labels:
        app: node-affinity-3
    spec:
      containers:
        - name: www-server
          image: hwchiu/netutils
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kind.zone
                    operator: In
                    values:
                      - zone1
                  - key: kind.zone
                    operator: In
                    values:
                      - zone2
